### PR TITLE
Updated to support Ansible Tower 3.1.3

### PR DESCRIPTION
**Pull request by amittell**
Added new image to DockerHub = lardos/ansibletower

### CODE REVIEW

**Comment by nicoecheza** [comment]
I just did this same thing on Monday.

Just tried your image, and it won't work since you are still executing the `apache` thing on the `docker-entrypoint.sh` file.

**Comment by nicoecheza** [comment]
Also, after commenting the line I pointed out, I've got this error message:

```
TASK [Gathering Facts] *********************************************************
fatal: [localhost]: UNREACHABLE! => {"changed": false, "msg": "[Errno None] Unable to connect to port 22 on 127.0.0.1 or ::1", "unreachable": true}
	to retry, use: --limit @/opt/tower-setup/install.retry```

**Comment by amittell** [comment]
The docker-entrypoint.sh file worked without modification for my build, check out the lardos/ansibletower image on DockerHub.

The localhost unreachable error from the tower install playbook is fixed by line 2 in the inventory file in the pull request. Did you use that modified inventory file for your docker build?

**Comment by nicoecheza** [comment]
I will try it again copying the inventory file since I think I messed up copying it from my own repo.

About the `docker-entrypoint.sh`, having an `Apache` config replacement doesn't make any sense since Ansible v3.1 doesn't use `Apache` anymore, it replaced it with `nginx`

**Comment by amittell** [comment]
Ok thanks for the info, those lines are redundant then, but they don't make the build fail so I never paid much attention to the entry point shell script. maybe worth commenting them out just for completeness.

**Comment by amittell** [comment]
@nicoecheza Updated the docker-entrypoint.sh based on your comments.

Removed tower_setup_conf.yml as duplicate to definitions in inventory file.

Changed version to 3.1.3 and cleaned up unnecessary packages from Dockerfile, rationalized, and updated README.

New Ansible Tower 3.1.3 image available at https://hub.docker.com/r/lardos/ansible-tower/

**Review by ybalt — COMMENTED** [review]
Looks good

**Comment by nicoecheza** [comment]
Nice work @amittell  👍

**Pull request merged**
